### ISSUE TITLE
Better configuration / options / grouping

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-module-styleguide#6]
We need a better way to configure the styleguide.
Currently, the default values for the styleguide are defined in the `elements.php` under `Views/`, I would suggest moving the definition to a separate styleguide config:

Example styleguide config:  
```php
[
    'groups' => [
        'buttons' => [
            'name' => 'Buttons',
            'description' => '...',
            'elements': [
                'button-primary': [
                    'name' => 'Button Primary',
                    'description' => '...',
                    'element' => 'button', // Name of the element that should be displayed (defined in elements.php)
                    'values' => ['Button Text', 'http://google.ch', 'danger'],
                    'options' => []
                ],
                'button-danger': [
                    'name' => 'Button Danger',
                    'description' => '...',
                    'element' => 'button', // Name of the element that should be displayed (defined in elements.php)
                    'values' => ['Button Text', 'http://google.ch', 'danger'],
                    'options' => [
                        'background': '#000', // If element needs a different background color
                        'min-height': '200', // If element is positioned absolutely
                        'overflow': false, // Enabled overflow: hidden on styleguide element container
                        'show-code': false, // Disabled output of sample code
                    ]
                ]
            ]
        ],
    ]
]
```

**Comment by nadar** [comment]
Maybe this is one of the very rare cases i would like to say this could make sense as yaml file.

+ it does not contain any application relation informations (in terms of security)
+ array configuration does not reflect the structure of an object

Maybe the styleguide could have an option like

```
`config' => '@app\elements.yaml'
```

**Comment by TheMaaarc** [comment]
@nadar You'll want to take a close look at:

* Is there a better way of passing the arguments? Also: The examples with ul/ol elements do not work because the parameter is an array and that seems to break the "..." "syntax". You're the expert! 💃 
https://github.com/luyadev/luya-module-styleguide/blob/2397c54b80400ebaf5608ae09e42e9d0af8338e2/src/views/default/index.php#L109

* I return the type of the var, because it might sometimes be an array and that would result in array to string conversion if we would return the value. Best would be something like `element(['asd', 'asd'])` I guess (instead of "array").
https://github.com/luyadev/luya-module-styleguide/blob/2397c54b80400ebaf5608ae09e42e9d0af8338e2/src/views/default/index.php#L115

**Comment by TheMaaarc** [comment]
The config array is just an idea, feel free to improve/change it. The options are not implemented yet, that will be the next step.
